texture_img: Texture_Data/big.png
grid_pixels: 256
uv_dim: 255.0
input_dir:  /home/arslanfarooq98/inference_dir/input_imgs
inference_dir: /home/arslanfarooq98/inference_dir
output_dir: /home/arslanfarooq98/inference_dir/output_results
tool_dir: /home/arslanfarooq98/modified_code/DensePose/tools
send_from: Output_Data
width: 1080
height: 720
