texture_img: Texture_Data\texture_from_SURREAL.png
grid_pixels: 200
input_dir:  /home/arslanfarooq98/inference_dir/input_imgs
inference_dir: /home/arslanfarooq98/inference_dir
output_dir: /home/arslanfarooq98/inference_dir/output_results